/* eslint-disable @next/next/no-img-element */
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div className="min-h-screen">
      <Head>
        <title>QR code component solution</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className="min-h-screen flex justify-center items-center">
        <div className="p-4 pb-8 w-fit bg-white rounded-2xl flex justify-center flex-col">
          <img
            src="/image-qr-code.png"
            alt="bar-code"
            className="rounded-xl max-w-xs"
          />
          <h1 className="mt-4 text-center p-2 font-bold text-darkBlue text-2xl max-w-xs ">
            Improve your front-end skills by building projects
          </h1>
          <p className="p-2 text-center text-lg text-grayishBlue max-w-xs ">
            Scan the QR code to visit Frontend Mentor and take your coding
            skills to the next level
          </p>
        </div>
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
