/* eslint-disable @next/next/no-img-element */
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div className="min-h-screen flex justify-center items-center">
      <Head>
        <title>QR code component solution</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className="p-3 pb-6 bg-white rounded-2xl flex justify-center flex-col items-center max-w-xs">
        <img
          src="/image-qr-code.png"
          alt="bar-code"
          className="rounded-xl max-w-xxs"
        />
        <h1 className="mt-4 text-center p-2 font-bold text-darkBlue text-2xl max-w-xxs ">
          Improve your front-end skills by building projects
        </h1>
        <p className="p-2 text-center text-md text-grayishBlue max-w-xxs ">
          Scan the QR code to visit Frontend Mentor and take your coding skills
          to the next level
        </p>
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
